"""empty message

Revision ID: 597d46f27eba
Revises: 
Create Date: 2018-10-02 16:18:38.978119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597d46f27eba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collect_email')
    # ### end Alembic commands ###
